name: publish

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Pnpm install
        uses: yuanze-dev/pnpm-install-with-cache@v2
        with:
          pnpm-version: 9

      - name: Build project
        run: pnpm build

      - name: Install lusun-scripts
        run: npm i -g lusun-scripts

      - name: Deploy to OSS
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESSKEYID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESSKEYSECRET }}
        run: |
          lusun-scripts deploy \
            --accessKeyId $ACCESS_KEY_ID \
            --accessKeySecret $ACCESS_KEY_SECRET \
            --target .vitepress/dist \
            --directoryPath tcq \
            --bucket docs-lusun-web \
            --endpoint oss-cn-beijing.aliyuncs.com

      - name: Feishu Notify
        env:
          FEISHU_ID: ${{ secrets.FEISHU_ID }}
          FEISHU_SECRET: ${{ secrets.FEISHU_SECRET }}
        run: |
          lusun-scripts feishu \
            --id $FEISHU_ID \
            --secret $FEISHU_SECRET \
            --message "{\"msg_type\": \"text\", \"content\": {\"text\": \"芦笋提词器帮助中心发布完成～ \n访问地址 https://docs.lusun.com/tcq \n执行人 ${GITHUB_ACTOR}\"}}"
